#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

set -eux

bazel run //hs-tokstyle/tools:check-cimple -- --markdown >"$SCRIPT_DIR/cimple.md"
bazel run //hs-tokstyle/tools:check-c -- --markdown >"$SCRIPT_DIR/c.md"
